QBTv1/AccountApp/urls.py
from django.urls import path
from . import views
from .views import QBTdetailView
from django.urls import include
app_name = 'AccountApp'

urlpatterns = [
    path('forms/', include('formapp.urls'), name="forms"),
    path('Home', views.TopPageView ,name="home"),
    path('user_create', views.UserCreateView.as_view(), name="user_create"),
    path('login', include('LoginApp.urls'), name="login"),
    path('logout', views.LogoutView.as_view(), name="logout"),
    path('det', QBTdetailView, name="detail"),
]

QBTv1/LoginApp/urls.py
from django.urls import path
from . import views
from django.urls import include

urlpatterns = [
    path('', views.Account_login.as_view(), name="login"),#会員登録ページへのパス
    
]

QBTv1/QBTv1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('QBTsys/', include('AccountApp.urls')),
]

QBTv1/formapp/urls.py
from django.urls import path
from . import views
from .views import SetQRparam

urlpatterns = [
    path('QBTForm', views.TestView.as_view(),name="formpage"),
    path('QRcode', SetQRparam ,name="qrcode"),
]

QBTv1/AccountApp/models.py
from django.db import models

QBTv1/LoginApp/models.py
from django.db import models

# Create your models here.

QBTv1/formapp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# モデルクラスを作成
class QBTModel(models.Model):
	# 項目定義
    StudentID     = models.CharField(max_length=150)
    TemperatureA    = models.IntegerField(validators=[MinValueValidator(32), MaxValueValidator(42)])
    TemperatureB    = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(9)])
    Q1 = models.BooleanField()
    Q2  = models.BooleanField()
    FreeText = models.TextField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    # テキスト表示
# Create your models here.

QBTv1/AccountApp/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
#フォームクラス作成

class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = User
       fields = ("username", "password1", "password2",)

QBTv1/LoginApp/forms.py
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       #htmlの表示を変更可能にします
       self.fields['username'].widget.attrs['class'] = 'form-control'
       self.fields['password'].widget.attrs['class'] = 'form-control'

QBTv1/formapp/forms.py
from django import forms
#モデルクラスを呼出
from .models import QBTModel
#フォームクラス作成
class QBTForm(forms.Form):
    
    TemperatureA = forms.ChoiceField(
        label='体温',
        choices = (
            (32, 32),
            (33, 33),
            (34, 34),
            (35, 35),
            (36, 36),
            (37, 37),
            (38, 38),
            (39, 39),
            (40, 40),
            (41, 41),
            (42, 42),
        ),
        initial=36,
        required=True,
        widget=forms.widgets.Select(),
    )

    TemperatureB = forms.ChoiceField(
        choices = (
            (0, 0),
            (1, 1),
            (2, 2),
            (3, 3),
            (4, 4),
            (5, 5),
            (6, 6),
            (7, 7),
            (8, 8),
            (9, 9),
        ),
        initial=0,
        required=True,
        widget=forms.widgets.Select(),
    )

    Q1 = forms.BooleanField(
        label='風邪症状はありますか？',
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'check'}),
    )

    Q2 = forms.BooleanField(
        label='倦怠感はありますか？',
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'check'}),
    )


    FreeText = forms.CharField(
        label = 'その他の症状',
        required=False, #必須項目か？
        max_length=100,
        widget=forms.Textarea,
    )    
    
    def save(self, username):
        # save data using the self.cleaned_data dictionary
        data = self.cleaned_data
        post = QBTModel(StudentID=username, TemperatureA=data['TemperatureA'], TemperatureB=data['TemperatureB'], Q1=data['Q1'], Q2=data['Q2'], FreeText=data['FreeText'])
        post.save()
 

QBTv1/AccountApp/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from formapp.models import QBTModel

#ホーム
def TopPageView(request):
    return render(request, 'TopPage.html')

#登録
class UserCreateView(CreateView):
    template_name = 'user_create.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('AccountApp:home')

#ログアウト
class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'TopPage.html'

#登録状況
def QBTdetailView(request):
    SID = request.user.username
    q = QBTModel.objects.filter(StudentID=SID).order_by('created_at').reverse()
    user_dict = {'QBTdet': q}
    return render(request, 'QBTdetail.html', context=user_dict)

QBTv1/LoginApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.views.generic import View
from . forms import LoginForm
#ログイン機能
class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('/QBTsys/Home')
        return render(request, 'login.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'login.html', {'form': form,})

account_login = Account_login.as_view()

QBTv1/formapp/views.py
from django.contrib import messages
from django.views.generic.edit import FormView
from formapp.forms import QBTForm
from django.shortcuts import render
from django.views.generic import View
from .models import QBTModel
from django.shortcuts import redirect

class TestView(FormView):
    template_name = 'App_Folder_HTML/formpage.html'
    form_class = QBTForm
    success_url = '/QBTsys/Home'  # リダイレクト先URL

    def form_valid(self, form):
        form.save(self.request.user.username)  # 保存処理など
        messages.add_message(self.request, messages.SUCCESS, '登録しました！')  # メッセージ出力
        return super().form_valid(form)


def SetQRparam(request):

    if request.user.is_authenticated:
        if (int(request.GET.get("tempA")) < 43) & (int(request.GET.get("tempA")) > 31) & (int(request.GET.get("tempB")) <= 9) & (int(request.GET.get("tempB")) >= 0):
            post = QBTModel(StudentID=request.user.username, TemperatureA=request.GET.get("tempA"), TemperatureB=request.GET.get("tempB"), Q1=request.GET.get("Q1"), Q2=request.GET.get("Q2"), FreeText='体温計からの記録')
            messages.add_message(request, messages.SUCCESS, '登録しました！')
            post.save()
        else:
            messages.add_message(request, messages.SUCCESS, '不正な値です')

    response = redirect('/QBTsys/Home')
    return response

QBTv1/templates/App_Folder_HTML/formpage.html
{% block content %}
    <h2>体温登録</h2>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <body>

    {% if user.id  %}

        {% with form as f %}

        <form method="post">{% csrf_token %}
        <div><label>{{ f.StudentID.label }}</label>: {{ f.StudentID }}</div>
        <div><label>{{ f.TemperatureA.label }}</label>: {{ f.TemperatureA }} . {{ f.TemperatureB }}</div>
        <div><label>{{ f.Q1.label }}</label>: {{ f.Q1 }}</div>
        <div><label>{{ f.Q2.label }}</label>: {{ f.Q2 }}</div>
        <div><label>{{ f.FreeText.label }}</label>: {{ f.FreeText }}</div>
            <input type="submit" value="送信">
        </form>

        {% endwith %}

    {% else %}   
        <p>あなたはまだログインしていません.</p>
        <a href="{% url 'AccountApp:home' %}">ホーム</a>
    {% endif %}

{% endblock %}

QBTv1/templates/QBTdetail.html
<!DOCTYPE html>
  <html>
      <head>
          <meta charset="utf-8">
          <title>
          </title>
      </head>
      <body>
  <h1>体温登録状況(最新順)</h1>

  {% if user.id  %}
  <a href="{% url 'AccountApp:home' %}">ホーム</a>
  {% if QBTdet %}

  <ol>
      {% for person in QBTdet %}

      <li>{{ person.created_at }} の登録</li>
      <ul>
          <li>体温: {{ person.TemperatureA}}.{{ person.TemperatureB}}</li>
          {% if person.Q1 == 1 %}
          <li>風邪症状: あり</li>
          {% elif person.Q1 == 0 %}
          <li>風邪症状: なし</li>
          {% endif %}
          {% if person.Q2 == 1 %}
          <li>倦怠感: あり</li>
          {% elif person.Q2 == 0 %}
          <li>倦怠感: なし</li>
          {% endif %}
          <li>自由記述: {{ person.FreeText }}</li>
      </ul>
  {% endfor %}
  </ol>
{% endif %}
  {% else %}   
      <p>あなたはまだログインしていません.</p>
      <a href="{% url 'AccountApp:home' %}">ホーム</a>
  {% endif %}

</body>
</html> 

QBTv1/templates/TopPage copy.html
<!DOCTYPE html>
<html lang="ja">
  <body>
    {% if user.id  %}
    <p>ログインしました．</p>
    <p>こんにちは，{{ user.username }}さん</p>
    <!--<a href="{% url 'logout' %}">ログアウトする</a>-->
    {% else %}
    <!--<a href="{% url 'login' %}">ログイン</a>-->
    <a href="{% url 'create_account' %}">アカウント作成</a>
    {% endif %}
  </body>
</html>

QBTv1/templates/TopPage.html
<!DOCTYPE html>
<html lang="ja">
  <title>体温登録システムホーム</title>
  <body>
    <h2>体温登録システムホーム</h2>
    {% if user.id  %}
    <p>ログインしました．</p>
    <p>こんにちは，{{ user.username }}さん</p>
    <a href="{% url 'AccountApp:logout' %}">ログアウトする</a>
    <a href="{% url 'AccountApp:formpage' %}">体温を登録する</a>
    <a href="{% url 'AccountApp:detail' %}">体温登録履歴</a>
    {% else %}
    <a href="{% url 'AccountApp:user_create' %}">アカウント作成</a>
    <a href="{% url 'AccountApp:login' %}">ログイン</a>
    {% endif %}

    {% if messages %}
    <div class="messages alert alert-primary" role="alert">
        {% for message in messages %}
          {{ message }}
        {% endfor %}
    </div>
    {% endif %}

  </body>
</html>

QBTv1/templates/login.html
<!DOCTYPE html>
<html lang="ja">
  <title>ログイン</title>
  <body>
    <h2>ログイン</h2>
    {% if form.errors  %}
    <p>ユーザーID, パスワードが一致しません．</p>
    {% endif %}
    <form method="POST" action="{% url 'AccountApp:login' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password }}
      {{ form.password.errors }}
      <button type = "submit">ログイン</button>
    </form>
  </body>
</html>

QBTv1/templates/user_create.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>アカウント作成</title>
</head>
<h2>アカウント作成</h2>
<body>
    <div>
        <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">登録</button>
        </form>
    </div>
</body>
</html>